version: "3"

services:
  fe:
    container_name: fe
    image: apache/doris:2.0.0_alpha-fe-x86_64
    hostname: fe
    environment:
     - FE_SERVERS=fe1:127.0.0.1:9010
     - FE_ID=1
    ports:
     - "9030:9030"
    volumes:
     - ./data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
     - ./data/fe/log/:/opt/apache-doris/fe/log/
    network_mode: 1panel-network
    labels:
      createdBy: "Apps"
  be:
    container_name: be
    image: apache/doris:2.0.0_alpha-be-x86_64
    hostname: be
    environment:
     - FE_SERVERS=fe1:127.0.0.1:9010
     - BE_ADDR=127.0.0.1:9050
    volumes:
     - ./data/be/storage/:/opt/apache-doris/be/storage/
     - ./data/be/script/:/docker-entrypoint-initdb.d/
    depends_on:
      - fe
    network_mode: 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true