version: "3"  
services:
  php81:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "${FastCGI_Server_PORT}:9000"
    volumes:
      - "./data/php.ini:/usr/local/etc/php/php.ini"
      - "./data/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "${Site_Path}:/www"
    labels:  
      createdBy: "Apps" 

networks:  
  1panel-network:  
    external: true


