version: '3'
services:
  memcached:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP1}:11211"
    command: memcached -m 64
    image: "memcached:1.6.19-alpine3.17"
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
