name: Update app version in Renovate Branches

on:
  push:
    branches: [ 'renovate/*' ]

jobs:
  update-app-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure repo
        run: |
          git config --local user.email "githubaction@githubaction.com"
          git config --local user.name "github-action update-app-version"

      - name: Get list of updated files by the last commit in this branch separated by space
        run: |
          echo "FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run renovate-app-version.sh on updated files
        run: |
          IFS=' ' read -ra files <<< "${{ env.FILES }}"

          for file in "${files[@]}"; do
            if [[ $file == *"docker-compose.yml"* ]]; then
              app_name=$(echo $file | cut -d'/' -f 2)
              old_version=$(echo $file | cut -d'/' -f 3)
              chmod +x .github/workflows/renovate-app-version.sh
              echo "$app_name $old_version" >> $GITHUB_STATE
            fi
          done

      - name: Commit & Push Changes
        run: |
          IFS=' ' read -ra files <<< "${{ env.FILES }}"

          for file in "${files[@]}"; do
            if [[ $file == *"docker-compose.yml"* ]]; then
              app_name=$(echo $file | cut -d'/' -f 2)
              git add "$app_name/*" && git commit -m "Update app version" --no-verify && git push origin localApps || true
            fi
          done
