name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - localApps
  workflow_dispatch:
    inputs:
      manual-trigger:
        description: 'Manually trigger Renovate'
        default: ''

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0
      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.4
        with:
          useSlim: false
          token: ${{ secrets.GITHUBTOKEN }}
